### ISSUE TITLE
Create SOP for selecting a battery

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Wiki#12]
We should write a page under the electrical subsection about how we select our batteries:
- using the beak, what values we want from it
- what charging LEDs mean
- etc.
@ACat701 or @Alenguye582 would either of you be willing to take this on?

**Comment by Alenguye582** [comment]
> We should write a page under the electrical subsection about how we select our batteries:
> 
> * using the beak, what values we want from it
> * what charging LEDs mean
> * etc.
>   @ACat701 or @Alenguye582 would either of you be willing to take this on?

I could try my best :3. I've never written a wiki page before but I'll look at our other pages for reference.
